apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: deploy-aap-instance
spec:
  serviceAccountName: pipelines
  params:
  - name: serviceNowIncidentID
    description: The ServiceNow incident ID
  - name: owner
    description: The owner of this AAP instance
  - name: branchName
    description: The name of the user's Branch
  - name: teamName
    description: The name of the user's Team
  - name: maxHosts
    description: The maximum amount of hosts this AAP instance can manage
    default: "20"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: deploy-aap-instance-
    spec:
      pipelineRef:
        name: deploy-aap-instance
      params:
      - name: serviceNowIncidentID
        value: $(tt.params.serviceNowIncidentID)
      - name: owner
        value: $(tt.params.author)
      - name: branchName
        value: $(tt.params.branchName)
      - name: teamName
        value: $(tt.params.teamName)
      - name: maxHosts
        value: $(tt.params.maxHosts)
      workspaces:
      - name: working-directory
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
