apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
namespace: aap-as-a-service
resources:
  - deploy-aap-instance.yml
  - modify-aap-instance.yml
