---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Ansible Automation Platform - Infrastructure Instance"
    openshift.io/display-name: "Ansible Automation Platform"
  name: aap-infra