[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore default MySQL Operator creds
    '''operators\/mattermost\/base\/mattermost-values.yml$''',
  ]