---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aap
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: aap-infra
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 2-operators/aap/overlays/stable-2.4
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service.git
    targetRevision: debug-eda-route
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true