---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Ansible Automation Platform as a Service"
    openshift.io/display-name: "AAPaaS"
    argocd.argoproj.io/managed-by: "openshift-gitops"
  name: aap-as-a-service