---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Red Hat OpenShift Pipelines"
    openshift.io/display-name: "Red Hat OpenShift Pipelines"
  name: openshift-pipelines