---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-gitops
  namespace: openshift-gitops
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: aap-as-a-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-admin