apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: aap-deploy-instance
spec:
  triggers:
    - name: servicenow-webhook
      interceptors:
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: "owner"
                  value: "body.author"
      bindings:
        - name: owner
          value: $(extensions.owner)
        - name: serviceNowIncidentID
          value: $(extensions.serviceNowIncidentID)
        - name: brancName
          value: $(extensions.branchName)
        - name: teamName
          value: $(extensions.teamName)
        - name: maxHosts
          value: $(extensions.maxHosts)
        - name: instanceID
          value: $(extensions.instanceID)
      template:
        ref: deploy-aap-instance
