apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: destroy-aap-instance
spec:
  triggers:
    - name: servicenow-webhook
      interceptors:
        # - name: "secretRef"
        #   value:
        #     secretName: webhook-secret
        #     secretKey: secretToken
        - ref:
            name: cel
          params:
            - name: "overlays"
              value:
                - key: owner
                  expression: body.author
                - key: serviceNowIncidentID
                  expression: body.serviceNowIncidentID
                - key: branchName
                  expression: body.branchName.lowerAscii().replace(" ", "-")
                - key: teamName
                  expression: body.teamName.lowerAscii().replace(" ", "-")
                - key: instanceID
                  expression: body.instanceID.lowerAscii().replace("AAP", "")
      bindings:
        - name: owner
          value: $(extensions.owner)
        - name: serviceNowIncidentID
          value: $(extensions.serviceNowIncidentID)
        - name: branchName
          value: $(extensions.branchName)
        - name: teamName
          value: $(extensions.teamName)
        - name: instanceID
          value: $(extensions.instanceID)
      template:
        ref: destroy-aap-instance
