apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - namespace.yml
  - operatorgroup.yml
  - subscription.yml
  - instance.yml
  - openshift-routes.yml