---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Red Hat OpenShift Certificate Manager Operator Project"
    openshift.io/display-name: "Red Hat OpenShift Certificate Manager"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: cert-manager-operator