---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Red Hat Ansible Automation Platform"
    openshift.io/display-name: "Red Hat Ansible Automation Platform"
  name: openshift-ansible-automation-platform