apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  generateName: deploy-aap-instance-
spec:
  workspaces:
    - name: working-directory
  params:
    - name: argocd-git-url
      type: string
      description: ArgoCD git repository URL
      default: git@github.com:ahussey-redhat/aap-as-a-service-gitops.git
  tasks:
    - name: update-servicenow-ticket-init
      taskRef:
        name: update-servicenow-ticket
    - name: clone-argocd-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.argocd-git-url)"
      workspaces:
        - name: output
          workspace: working-directory
      runAfter:
        - update-servicenow-ticket-init
    - name: update-servicenow-ticket-clone
      taskRef:
        name: update-servicenow-ticket
      runAfter:
        - clone-argocd-repository
    - name: deploy-aap-instance
      taskRef:
        name: deploy-aap-instance
      runAfter:
        - clone-argocd-repository
      workspaces:
        - name: output
          workspace: working-directory
  finally:
    - name: update-servicenow-ticket-complete
      taskRef:
        name: update-servicenow-ticket