apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-aap-instance
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  workspaces:
    - name: working-directory
  params:
    - name: argocd-git-url
      type: string
      description: ArgoCD git repository URL
      default: git@github.com:ahussey-redhat/aap-as-a-service-gitops.git
    - name: ticketID
      type: string
      description: The ServiceNow ticket ID used for provisioning the AAP instance
  tasks:
    - name: update-servicenow-ticket-init
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: initiating
        - name: ticketID
          value: "$(params.ticketID)"
    - name: clone-argocd-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.argocd-git-url)"
      workspaces:
        - name: output
          workspace: working-directory
      runAfter:
        - update-servicenow-ticket-init
    - name: update-servicenow-ticket-deploy
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: deploying
        - name: ticketID
          value: "$(params.ticketID)"
      runAfter:
        - clone-argocd-repository
    - name: deploy-aap-instance
      taskRef:
        name: deploy-aap-instance
      runAfter:
        - clone-argocd-repository
      workspaces:
        - name: output
          workspace: working-directory
    - name: update-servicenow-ticket-complete
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: complete
        - name: ticketID
          value: "$(params.ticketID)"
      runAfter:
        - deploy-aap-instance
        - update-servicenow-ticket-deploy
  finally:
    - name: update-servicenow-ticket-failed
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: failed
        - name: ticketID
          value: "$(params.ticketID)"