apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-aap-instance
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  workspaces:
    - name: working-directory
  params:
    - name: argocd-git-url
      type: string
      description: ArgoCD git repository URL
      default: git@github.com:ahussey-redhat/aap-as-a-service-gitops.git
    - name: serviceNowIncidentID
      type: string
      description: The ServiceNow ticket ID used for provisioning the AAP instance
    - name: branchName
      type: string
      description: Name of user's Branch EG 'Enterprise IT'
    - name: teamName
      type: string
      description: Name of user's Team EG 'Kubernetes'
    - name: maxHosts
      type: string
      description: The maximum number of hosts this AAP instance can manage
      default: "20"
    - name: owner
      type: string
      description: Owner of the SericeNow request/AAP instance
    - name: instanceID
      type: string
      description: Iterative number associated with this AAP instance
  tasks:
    - name: update-servicenow-ticket-init
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: initiating
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
    - name: clone-argocd-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.argocd-git-url)"
      workspaces:
        - name: output
          workspace: working-directory
      runAfter:
        - update-servicenow-ticket-init
    - name: update-servicenow-ticket-deploy
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: deploying
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
      runAfter:
        - clone-argocd-repository
    - name: deploy-aap-instance
      taskRef:
        name: deploy-aap-instance
      runAfter:
        - update-servicenow-ticket-deploy
      workspaces:
        - name: output
          workspace: working-directory
    - name: update-servicenow-ticket-deployed
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: deployed
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
      runAfter:
        - deploy-aap-instance
    - name: conduct-day2-ops
      taskRef:
        name: day2-ops
      params:
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: maxHosts
          value: "$(params.maxHosts)"
      runAfter:
        - update-servicenow-ticket-deployed
    - name: update-servicenow-ticket-complete
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: complete
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
      runAfter:
        - conduct-day2-ops
  finally:
    - name: update-servicenow-ticket-failed
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: state
          value: failed
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
