apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: destroy-aap-instance
spec:
  workspaces:
    - name: working-directory
    - name: ssh-creds
  params:
    - name: argocd-git-url
      type: string
      description: ArgoCD git repository URL
      default: git@github.com:ahussey-redhat/aap-as-a-service-gitops.git
    - name: serviceNowIncidentID
      type: string
      description: The ServiceNow ticket ID used for provisioning the AAP instance
    - name: branchName
      type: string
      description: Name of user's Branch EG 'Enterprise IT'
    - name: teamName
      type: string
      description: Name of user's Team EG 'Kubernetes'
    - name: owner
      type: string
      description: Owner of the SericeNow request/AAP instance
    - name: instanceID
      type: string
      description: Iterative number associated with this AAP instance
  tasks:
    - name: update-servicenow-ticket-init
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: status
          value: initiating
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
    - name: clone-argocd-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.argocd-git-url)"
      workspaces:
        - name: output
          workspace: working-directory
        - name: ssh-directory
          workspace: ssh-creds
      runAfter:
        - update-servicenow-ticket-init
    - name: update-servicenow-ticket-destroy
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: status
          value: initiating
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
      runAfter:
        - clone-argocd-repository
    - name: destroy-aap-instance
      taskRef:
        name: destroy-aap-instance
      params:
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
      runAfter:
        - update-servicenow-ticket-destroy
      workspaces:
        - name: output
          workspace: working-directory
        - name: ssh-directory
          workspace: ssh-creds
    - name: update-servicenow-ticket-deployed
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: status
          value: initiating
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
      runAfter:
        - destroy-aap-instance
    - name: update-servicenow-ticket-complete
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: status
          value: complete # ensure to add a comment saying it can take upto 10 minutes for the instance to be fully available
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
      runAfter:
        - update-servicenow-ticket-deployed
  finally:
    - name: update-servicenow-ticket-failed
      taskRef:
        name: update-servicenow-ticket
      params:
        - name: status
          value: initiating
        - name: serviceNowIncidentID
          value: "$(params.serviceNowIncidentID)"
        - name: owner
          value: "$(params.owner)"
        - name: branchName
          value: "$(params.branchName)"
        - name: teamName
          value: "$(params.teamName)"
        - name: instanceID
          value: "$(params.instanceID)"
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Failed"]
