apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aap-as-a-service
commonAnnotations:
    argocd.argoproj.io/sync-wave: "3"
resources:
  - deploy-aap-instance.yml
  - modify-aap-instance.yml
  - destroy-aap-instance.yml