# WIP
# This task should:
# 1. create CRD instances to create an organization within the AAP instance
# 2. configure SSO for external auth
# 3. sync content for PAH
# 4. configure logging and metrics
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: deploy aap instance
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: aap
  name: conduct-day2-ops
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: ahussey
spec:
  description: >-
    This task runs all the commands required to deploy an AAP instance.
  params:
    - default: "20"
      description: The max number of managed nodes
      name: maxHosts
      type: string
    - description: Branch name
      name: branchName
      type: string
    - description: Team name
      name: teamName
      type: string
    - description: AAP instance owner
      name: owner
      type: string
    - description: ServiceNow incident ID
      name: serviceNowIncidentID
      type: string
  steps:
    # Update appropriate variables for the AAP instance
    - name: kustomize-aap-instance
      image: >-
        registry.redhat.io/devspaces/udi-rhel8:latest
      resources: {}
      script: |
        #!/usr/bin/env bash

        cd environments/${branchName}-${teamName}-${instanceNumber}

        # Configure AAP ArgoCD application name
        kustomize edit set metadata.name=${branchName}-${teamName}-${instanceNumber} environments/${branchName}-${teamName}/${instanceNumber}/application.yml
        # Configure AAP ArgoCD application namespace
        kustomize edit set metadata.namespace=${branchName}-${teamName} environments/${branchName}-${teamName}/${instanceNumber}/application.yml

        # Configure AAP application namespace
        kustomize edit set namespace=${branchName}-${teamName} environments/${branchName}-${teamName}/${instanceNumber}/kustomization.yaml
        
        # Configure ArgoCD application labels
        kustomize edit set metadata.labels.servicenowincidentid=${serviceNowIncidentID} environments/${branchName}-${teamName}/${instanceNumber}/application.yml
        kustomize edit set metadata.labels.owner=${owner} environments/${branchName}-${teamName}/${instanceNumber}/application.yml

        # Configure AAP instance name
        yq -ei '.metadata.name = "${branchName}-${teamName}-${instanceNumber}"' environments/${branchName}-${teamName}/${instanceNumber}/aap-instance/base/instance.yml

    # Push changes to ArgoCD repo
    - name: git-push
      image: >-
        registry.redhat.io/devspaces/udi-rhel8:latest
      resources: {}
      script: |
        #!/usr/bin/env bash
      
        git config --global user.name $(params.owner)
        git config --global user.email $(params.owner)@example.com
        git add --all
        git commit -m "Add ${branchOrTeamName}-${instanceNumber} environment"
        git push -u origin main -f

  # Workspace definitions
  workspaces:
    - description: >-
        The workspace which contains kubernetes manifests which we want to apply
        on the cluster.
      name: manifest-dir
      optional: true
    - description: >-
        The workspace which contains the the kubeconfig file if in case we want
        to run the oc command on another cluster.
      name: kubeconfig-dir
      optional: true
    - description: >-
        The workspace which contains the ArgoCD cloned git repository
      name: argocd-dir
      optional: false
