apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
    argocd.argoproj.io/sync-wave: "3"
namespace: aap-as-a-service
resources:
  - prepare-aap-instance.yml
  - customise-aap-instance.yml
  - deploy-aap-instance.yml
  - conduct-day1-ops.yml
  - conduct-day2-ops.yml
  - update-servicenow-ticket.yml
  - modify-aap-instance.yml
  - destroy-aap-instance.yml
