apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-test- 
  namespace: build-test
spec:
  params:
    - name: url
      value: "git@github.com:ahussey-redhat/keycloak-deploy.git"
    - name: revision
      value: main
  taskRef:
    kind: ClusterTask
    name: git-clone
  workspaces:
    - name: output
      emptyDir: {}