# WIP
# This should:
# 1. Update a ServiceNow incident with a specific status about the AAP instance being managed
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Update ServiceNow Incident
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: aap, servicenow
  name: update-servicenow-ticket
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: ahussey
spec:
  params:
  - name: serviceNowIncidentID
    description: The ServiceNow Incident ID number
    type: string
  - name: owner
    description: The requester of the AAP instance
    type: string
  - name: branchName
    description: The name of the Branch the requester belongs to
    type: string
  - name: teamName
    description: The name of the Team the requester belongs to
    type: string
  - name: instanceID
    description: The unique number associated with this instance
    type: string
  - name: message
    description: The message to put in the ServiceNow Incident
    type: string
    default: ""
  steps:
    - name: update-incident
      resources: {}
      env:
        - name: SNOW_USER
          valueFrom:
            secretKeyRef:
              name: servicenow
              key: user
        - name: SNOW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: servicenow
              key: secret
        - name: SNOW_INSTANCE
          valueFrom:
            secretKeyRef:
              name: servicenow
              key: instance
      image: >-
        registry.redhat.io/devspaces/udi-rhel8:latest
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        export SERVICE_NOW_INCIDENT_ID="$(params.serviceNowIncidentID)"
        export MESSAGE="$(params.message)"
        if [[ ! ${MESSAGE} ]]; then
          echo "Updating ServiceNow ticket: ${SERVICE_NOW_INCIDENT_ID}"
          echo "$(params.branchName)/$(params.teamName)/$(params.owner) AAP instance: $(params.instanceID)"
        else
          echo "$(params.message)"
            curl -u "${SNOW_USER}:${SNOW_PASSWORD}" \
              --request PUT \
              --header "Accept:application/json" \
              --header "Content-Type:application/json" \
              --data "{\"work_notes\":\"${MESSAGE}\"}" \
              "${SNOW_INSTANCE}/api/now/table/sc_request/${SERVICE_NOW_INCIDENT_ID}"
           if [[ $? != 0 ]]; then
              echo "${MESSAGE}"
              exit 0
           fi
        fi