# WIP
# This should:
# 1. Update a ServiceNow incident with a specific status about the AAP instance being managed
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: Update ServiceNow Incident
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/tags: aap, servicenow
  name: update-servicenow-ticket
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    operator.tekton.dev/provider-type: ahussey
spec:
  params:
  - name: serviceNowIncidentID
    description: The ServiceNow Incident ID number
    type: string
  - name: owner
    description: The requester of the AAP instance
    type: string
  - name: branchName
    description: The name of the Branch the requester belongs to
    type: string
  - name: teamName
    description: The name of the Team the requester belongs to
    type: string
  - name: instanceID
    description: The unique number associated with this instance
    type: string
  - name: status
    description: The status to update the incident with
    type: string
  - name: message
    description: The message to put in the ServiceNow Incident
    type: string
    default: ""
  steps:
    - name: update-incident
      resources: {}
      image: >-
        registry.redhat.io/devspaces/udi-rhel8:latest
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail
        MESSAGE="$(params.message)"
        if [[ ! ${MESSAGE} ]]; then
          echo "Updating ServiceNow ticket: $(params.serviceNowIncidentID) with status: $(params.status)"
          echo "$(params.branchName)/$(params.teamName)/$(params.owner) requesting AAP instance: $(params.instanceID)"
          echo "Currently this is a NOOP"
        else
          echo "$(params.message)"
        fi