---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: operators/rhsso/overlays/alpha
    repoURL: >-
      https://github.com/ahussey-redhat/aap-as-a-service.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true