---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "Red Hat OpenShift Dev Spaces Project"
    openshift.io/display-name: "Red Hat OpenShift Dev Spaces"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-devspaces